# Generated by Django 5.2.6 on 2025-10-20 03:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sync', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='syncconflict',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='syncconflict',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
