# Generated by Django 5.2.6 on 2025-09-27 23:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('farms', '0002_shed'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Flock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('arrival_date', models.DateField()),
                ('initial_quantity', models.PositiveIntegerField()),
                ('current_quantity', models.PositiveIntegerField()),
                ('initial_weight', models.DecimalField(decimal_places=2, max_digits=5)),
                ('breed', models.CharField(max_length=50)),
                ('gender', models.CharField(choices=[('M', 'Macho'), ('F', 'Hembra'), ('X', 'Mixto')], max_length=1)),
                ('supplier', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('ACTIVE', 'Activo'), ('SOLD', 'Vendido'), ('FINISHED', 'Terminado'), ('TRANSFERRED', 'Transferido')], default='ACTIVE', max_length=12)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_flocks', to=settings.AUTH_USER_MODEL)),
                ('shed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flocks', to='farms.shed')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
