# Generated by Django 5.2.6 on 2025-09-27 23:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flocks', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BreedReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('breed', models.CharField(max_length=100)),
                ('age_days', models.PositiveIntegerField()),
                ('expected_weight', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
            options={
                'unique_together': {('breed', 'age_days')},
            },
        ),
        migrations.CreateModel(
            name='DailyWeightRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('average_weight', models.DecimalField(decimal_places=2, max_digits=6)),
                ('sample_size', models.PositiveIntegerField(default=10)),
                ('expected_weight', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('deviation_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('client_id', models.CharField(blank=True, max_length=50, null=True)),
                ('sync_status', models.CharField(default='SYNCED', max_length=20)),
                ('created_by_device', models.CharField(blank=True, max_length=100, null=True)),
                ('flock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weight_records', to='flocks.flock')),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('flock', 'date')},
            },
        ),
    ]
