# Generated by Django 5.2.6 on 2025-09-28 05:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flocks', '0002_breedreference_dailyweightrecord'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MortalityCause',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('category', models.CharField(choices=[('DISEASE', 'Enfermedad'), ('ENVIRONMENTAL', 'Ambiental'), ('NUTRITIONAL', 'Nutricional'), ('UNKNOWN', 'Desconocida'), ('OTHER', 'Otra')], max_length=50)),
                ('requires_veterinary', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MortalityRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('deaths', models.PositiveIntegerField()),
                ('temperature', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('notes', models.TextField(blank=True)),
                ('client_id', models.CharField(blank=True, max_length=50, null=True)),
                ('sync_status', models.CharField(default='SYNCED', max_length=20)),
                ('created_by_device', models.CharField(blank=True, max_length=100, null=True)),
                ('cause', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='flocks.mortalitycause')),
                ('flock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mortality_records', to='flocks.flock')),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('flock', 'date')},
            },
        ),
    ]
