# Generated by Django 5.2.6 on 2025-10-25 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flocks', '0005_alter_breedreference_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flock',
            name='current_quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
