# Generated by Django 5.2.6 on 2025-10-20 03:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reportschedule',
            options={'ordering': ['-created_at']},
        ),
    ]
