# Generated by Django 5.2.6 on 2025-09-27 23:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farms', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Shed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('capacity', models.PositiveIntegerField()),
                ('assigned_worker', models.ForeignKey(blank=True, limit_choices_to={'role__name': 'Galponero'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_sheds', to=settings.AUTH_USER_MODEL)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sheds', to='farms.farm')),
            ],
            options={
                'indexes': [models.Index(fields=['farm', 'name'], name='farms_shed_farm_id_ef4d84_idx'), models.Index(fields=['assigned_worker'], name='farms_shed_assigne_593fbc_idx')],
                'unique_together': {('name', 'farm')},
            },
        ),
    ]
