# Generated by Django 5.2.6 on 2025-09-28 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foodconsumptionrecord',
            name='flock',
        ),
        migrations.RemoveField(
            model_name='foodconsumptionrecord',
            name='inventory_item',
        ),
        migrations.RemoveField(
            model_name='foodconsumptionrecord',
            name='recorded_by',
        ),
        migrations.RemoveField(
            model_name='inventoryitem',
            name='farm',
        ),
        migrations.RemoveField(
            model_name='inventoryitem',
            name='shed',
        ),
        migrations.DeleteModel(
            name='FoodBatch',
        ),
        migrations.DeleteModel(
            name='FoodConsumptionRecord',
        ),
        migrations.DeleteModel(
            name='InventoryItem',
        ),
    ]
