# Generated by Django 5.2.6 on 2025-09-28 17:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('farms', '0002_shed'),
        ('inventory', '0002_remove_foodconsumptionrecord_flock_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('current_stock', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('unit', models.CharField(choices=[('KG', 'Kilogramos'), ('TON', 'Toneladas'), ('BAG', 'Sacos'), ('LB', 'Libras')], max_length=30)),
                ('minimum_stock', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('daily_avg_consumption', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('last_restock_date', models.DateField(blank=True, null=True)),
                ('last_consumption_date', models.DateField(blank=True, null=True)),
                ('alert_threshold_days', models.PositiveIntegerField(default=5)),
                ('critical_threshold_days', models.PositiveIntegerField(default=2)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to='farms.farm')),
                ('shed', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to='farms.shed')),
            ],
            options={
                'unique_together': {('name', 'farm', 'shed')},
            },
        ),
        migrations.CreateModel(
            name='InventoryConsumptionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('quantity_consumed', models.DecimalField(decimal_places=2, max_digits=12)),
                ('inventory_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consumption_records', to='inventory.inventoryitem')),
            ],
            options={
                'unique_together': {('inventory_item', 'date')},
            },
        ),
    ]
