# Generated by Django 5.2.6 on 2025-09-29 03:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flocks', '0005_alter_breedreference_options_and_more'),
        ('inventory', '0003_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_date', models.DateField()),
                ('initial_quantity', models.DecimalField(decimal_places=2, max_digits=12)),
                ('current_quantity', models.DecimalField(decimal_places=2, max_digits=12)),
                ('supplier', models.CharField(blank=True, max_length=100)),
                ('lot_number', models.CharField(blank=True, max_length=50)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('inventory_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food_batches', to='inventory.inventoryitem')),
            ],
            options={
                'ordering': ['entry_date'],
                'indexes': [models.Index(fields=['inventory_item', 'entry_date'], name='inventory_f_invento_2f3abe_idx'), models.Index(fields=['current_quantity'], name='inventory_f_current_d6d9cd_idx')],
            },
        ),
        migrations.CreateModel(
            name='FoodConsumptionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('quantity_consumed', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fifo_details', models.JSONField(help_text='Detalles de qué lotes se consumieron')),
                ('client_id', models.CharField(blank=True, max_length=50, null=True)),
                ('sync_status', models.CharField(default='SYNCED', max_length=20)),
                ('created_by_device', models.CharField(blank=True, max_length=100, null=True)),
                ('flock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food_consumption_records', to='flocks.flock')),
                ('inventory_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flock_consumption_records', to='inventory.inventoryitem')),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['date', 'flock'], name='inventory_f_date_d3172d_idx'), models.Index(fields=['sync_status'], name='inventory_f_sync_st_19fac1_idx')],
                'unique_together': {('flock', 'inventory_item', 'date')},
            },
        ),
    ]
