# Generated by Django 5.2.6 on 2025-09-29 02:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('farms', '0002_shed'),
        ('flocks', '0005_alter_breedreference_options_and_more'),
        ('inventory', '0003_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AlarmConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('alarm_type', models.CharField(choices=[('MORTALITY', 'Mortalidad Alta'), ('WEIGHT', 'Peso Fuera de Rango'), ('STOCK', 'Stock Crítico'), ('CONSUMPTION', 'Consumo Anómalo'), ('NO_RECORDS', 'Sin Registros')], max_length=20)),
                ('threshold_value', models.DecimalField(decimal_places=2, max_digits=8)),
                ('critical_threshold', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('evaluation_period_hours', models.PositiveIntegerField(default=24)),
                ('consecutive_occurrences', models.PositiveIntegerField(default=1)),
                ('notify_farm_manager', models.BooleanField(default=True)),
                ('notify_veterinarian', models.BooleanField(default=True)),
                ('notify_galponeros', models.BooleanField(default=False)),
                ('escalate_after_hours', models.PositiveIntegerField(blank=True, null=True)),
                ('escalate_to_admin', models.BooleanField(default=False)),
                ('escalation_role_name', models.CharField(blank=True, max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alarm_configs', to='farms.farm')),
            ],
            options={
                'unique_together': {('alarm_type', 'farm')},
            },
        ),
        migrations.CreateModel(
            name='Alarm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('alarm_type', models.CharField(max_length=20)),
                ('description', models.TextField()),
                ('priority', models.CharField(default='MEDIUM', max_length=20)),
                ('source_type', models.CharField(blank=True, max_length=30, null=True)),
                ('source_date', models.DateField(blank=True, null=True)),
                ('source_id', models.BigIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente'), ('RESOLVED', 'Resuelta'), ('ESCALATED', 'Escalada')], default='PENDING', max_length=20)),
                ('farm', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='farms.farm')),
                ('flock', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='flocks.flock')),
                ('inventory_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.inventoryitem')),
                ('shed', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='farms.shed')),
                ('configuration', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='alarms.alarmconfiguration')),
            ],
        ),
        migrations.CreateModel(
            name='AlarmEscalation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('escalation_reason', models.CharField(max_length=100)),
                ('escalated_at', models.DateTimeField(auto_now_add=True)),
                ('alarm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='escalations', to='alarms.alarm')),
                ('escalated_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notification_type', models.CharField(choices=[('PUSH', 'Push'), ('EMAIL', 'Email'), ('SMS', 'SMS')], max_length=20)),
                ('status', models.CharField(choices=[('SENT', 'Sent'), ('ERROR', 'Error'), ('DELIVERED', 'Delivered')], max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('alarm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_logs', to='alarms.alarm')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='alarm',
            index=models.Index(fields=['source_type', 'source_date'], name='alarms_alar_source__dd5ab9_idx'),
        ),
        migrations.AddIndex(
            model_name='alarm',
            index=models.Index(fields=['farm', 'flock'], name='alarms_alar_farm_id_09250b_idx'),
        ),
    ]
