# Generated by Django 5.2.6 on 2025-09-29 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alarms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alarmconfiguration',
            name='alarm_type',
            field=models.CharField(choices=[('MORTALITY', 'Mortalidad Alta'), ('WEIGHT', 'Peso Fuera de Rango'), ('WEIGHT_DEVIATION', 'Desviación de Peso'), ('STOCK', 'Stock Crítico'), ('CONSUMPTION', 'Consumo Anómalo'), ('NO_RECORDS', 'Sin Registros')], max_length=20),
        ),
    ]
